/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_cuoikhoa_javabase;

import javax.swing.JOptionPane;
import project_cuoikhoa_javabase.BanHang.frmBanHang;
import project_cuoikhoa_javabase.BanHang.frmHoaDonBanHang;
import project_cuoikhoa_javabase.HangHoa.frmHangHoa;
import project_cuoikhoa_javabase.KhachHang.frmKhachHang;
import project_cuoikhoa_javabase.dangnhap.frmDangKy;
import project_cuoikhoa_javabase.dangnhap.frmDangNhap;
import project_cuoikhoa_javabase.dangnhap.frmDangNhap.LoginCallback;
import project_cuoikhoa_javabase.dangnhap.frmTaiKhoan;
import project_cuoikhoa_javabase.muahang.frmHoaDonMua;
import project_cuoikhoa_javabase.muahang.frmToaHoaDonMua;
import project_cuoikhoa_javabase.nguoidung.NguoiDung;
import project_cuoikhoa_javabase.nguoidung.NguoiDungBusiness;
import project_cuoikhoa_javabase.nguoidung.frmDanhSachNguoiDung;
import project_cuoikhoa_javabase.nguoidung.frmNguoiDungAdd;

/**
 *
 * @author minhp
 */
public class frmTrangChu extends javax.swing.JFrame {

    /**
     * Creates new form frmTrangChu
     */
    public static boolean isTrangThaiDangNhap = false;

    public static String userName = "";
    public static int userId = 0;

    public frmTrangChu() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        lblTrangThai = new javax.swing.JLabel();
        lblDangNhap = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHeThong = new javax.swing.JMenu();
        menuItemNguoiDung = new javax.swing.JMenuItem();
        menuItemKhachHang = new javax.swing.JMenuItem();
        menuItemTaiKhoan = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuItemDangNhap = new javax.swing.JMenuItem();
        menuItemDangXuat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuItemThoat = new javax.swing.JMenuItem();
        menuNgiepVu = new javax.swing.JMenu();
        menuItemTaoHoaDonBanHang = new javax.swing.JMenuItem();
        menuItemTaoHoaDonMua = new javax.swing.JMenuItem();
        menuHangHoa = new javax.swing.JMenu();
        menuItemHangHoa = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuItemHoaDonBanHang = new javax.swing.JMenuItem();
        menuItemHoaDonMua = new javax.swing.JMenuItem();
        menuTroGiup = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTrangThai.setText("jLabel1");
        lblTrangThai.setToolTipText("");

        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDangNhap.setText("Bạn đang đăng nhập với tài khoản:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTrangThai)
                    .addComponent(lblDangNhap))
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 447, 730, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_cuoikhoa_javabase/res/laptop-man-hinh-full-hd-la-gi-kinh-nghiem-chon-mu-2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -9, -1, 470));

        menuHeThong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_cuoikhoa_javabase/Images/settings_16.png"))); // NOI18N
        menuHeThong.setText("Hệ thống");

        menuItemNguoiDung.setText("Người dùng");
        menuItemNguoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNguoiDungActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemNguoiDung);

        menuItemKhachHang.setText("Khách hàng");
        menuItemKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKhachHangActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemKhachHang);

        menuItemTaiKhoan.setText("Tài khoản");
        menuItemTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTaiKhoanActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemTaiKhoan);
        menuHeThong.add(jSeparator2);

        menuItemDangNhap.setText("Đăng nhập");
        menuItemDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangNhapActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemDangNhap);

        menuItemDangXuat.setText("Đăng xuất");
        menuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangXuatActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemDangXuat);
        menuHeThong.add(jSeparator3);

        menuItemThoat.setText("Thoát ");
        menuItemThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemThoatActionPerformed(evt);
            }
        });
        menuHeThong.add(menuItemThoat);

        jMenuBar1.add(menuHeThong);

        menuNgiepVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_cuoikhoa_javabase/Images/List_BulletsHS.png"))); // NOI18N
        menuNgiepVu.setText("Nghiệp vụ");

        menuItemTaoHoaDonBanHang.setText("Tạo hóa đơn bán hàng");
        menuItemTaoHoaDonBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTaoHoaDonBanHangActionPerformed(evt);
            }
        });
        menuNgiepVu.add(menuItemTaoHoaDonBanHang);

        menuItemTaoHoaDonMua.setText("Tạo hóa đơn mua hàng");
        menuItemTaoHoaDonMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTaoHoaDonMuaActionPerformed(evt);
            }
        });
        menuNgiepVu.add(menuItemTaoHoaDonMua);

        jMenuBar1.add(menuNgiepVu);

        menuHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_cuoikhoa_javabase/Images/graphhs.png"))); // NOI18N
        menuHangHoa.setText("Hàng hóa");

        menuItemHangHoa.setText("Hàng hóa");
        menuItemHangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHangHoaActionPerformed(evt);
            }
        });
        menuHangHoa.add(menuItemHangHoa);
        menuHangHoa.add(jSeparator4);

        menuItemHoaDonBanHang.setText("Hóa đơn bán hàng");
        menuItemHoaDonBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHoaDonBanHangActionPerformed(evt);
            }
        });
        menuHangHoa.add(menuItemHoaDonBanHang);

        menuItemHoaDonMua.setText("Hóa đơn mua hàng");
        menuItemHoaDonMua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemHoaDonMuaActionPerformed(evt);
            }
        });
        menuHangHoa.add(menuItemHoaDonMua);

        jMenuBar1.add(menuHangHoa);

        menuTroGiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project_cuoikhoa_javabase/Images/Help.png"))); // NOI18N
        menuTroGiup.setText("Trợ giúp");
        jMenuBar1.add(menuTroGiup);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNguoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNguoiDungActionPerformed
        frmDanhSachNguoiDung danhsach = new frmDanhSachNguoiDung();
        danhsach.setVisible(true);

    }//GEN-LAST:event_menuItemNguoiDungActionPerformed

    private void menuItemTaoHoaDonBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTaoHoaDonBanHangActionPerformed
        // TODO add your handling code here:
        frmBanHang banhang = new frmBanHang();
        banhang.setVisible(true);

    }//GEN-LAST:event_menuItemTaoHoaDonBanHangActionPerformed

    private void menuItemHangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHangHoaActionPerformed
        // TODO add your handling code here:
        frmHangHoa hanghoa = new frmHangHoa();
        hanghoa.setVisible(true);
    }//GEN-LAST:event_menuItemHangHoaActionPerformed

    private void menuItemThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemThoatActionPerformed

    private void menuItemKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKhachHangActionPerformed
        // TODO add your handling code here:
        frmKhachHang khachHang = new frmKhachHang();
        khachHang.setVisible(true);
    }//GEN-LAST:event_menuItemKhachHangActionPerformed

    private void menuItemHoaDonBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHoaDonBanHangActionPerformed
        // TODO add your handling code here:
        frmHoaDonBanHang banhang = new frmHoaDonBanHang();
        banhang.setVisible(true);
    }//GEN-LAST:event_menuItemHoaDonBanHangActionPerformed

    private void menuItemDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangNhapActionPerformed
        frmDangNhap frmLogin = new frmDangNhap(new LoginCallback() {
            @Override
            public void onLoginSuccess(String tenDangNhap) {
                NguoiDungBusiness bus = new NguoiDungBusiness();
                NguoiDung objUser = bus.layThongTinDangNhap(tenDangNhap);

                if (objUser != null) {
                    String quyen = objUser.getQuyen(); // Lấy quyền của người dùng từ cơ sở dữ liệu
                    kiemTraQuyenSuDung(quyen, objUser.getTenDangNhap());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Đăng nhập thất bại. Tài khoản không tồn tại.");
                }
            }
        });

        frmLogin.setVisible(true);
    }//GEN-LAST:event_menuItemDangNhapActionPerformed

    private void menuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangXuatActionPerformed

        this.dispose();

        frmTrangChu trangChu = new frmTrangChu();
        trangChu.setVisible(true);

    }//GEN-LAST:event_menuItemDangXuatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (isTrangThaiDangNhap) {
            NguoiDungBusiness bus = new NguoiDungBusiness();
            NguoiDung objUser = bus.layThongTinDangNhap(userName);

            if (objUser != null) {
                String quyen = objUser.getQuyen();
                kiemTraQuyenSuDung(quyen, userName);
            }
        } else {
            kiemTraQuyenSuDung(null, null);
        }
    }//GEN-LAST:event_formWindowOpened

    private void menuItemTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTaiKhoanActionPerformed
        String tenDangNhap = "";

        tenDangNhap = lblTrangThai.getText();

        frmTaiKhoan frmSua = new frmTaiKhoan();

        frmSua.setTenDangNhap(tenDangNhap);

        //Hiển thị form
        frmSua.setVisible(true);

    }//GEN-LAST:event_menuItemTaiKhoanActionPerformed

    private void menuItemTaoHoaDonMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTaoHoaDonMuaActionPerformed
        // TODO add your handling code here:
        frmToaHoaDonMua hoaDonMua = new frmToaHoaDonMua();
        
        hoaDonMua.setVisible(true);
    }//GEN-LAST:event_menuItemTaoHoaDonMuaActionPerformed

    private void menuItemHoaDonMuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemHoaDonMuaActionPerformed
        frmHoaDonMua HoaDonMua = new frmHoaDonMua();
        
        HoaDonMua.setVisible(true);
    }//GEN-LAST:event_menuItemHoaDonMuaActionPerformed

    private void dangNhapHeThong() {
        frmDangNhap frmLogin = new frmDangNhap();
        frmLogin.setVisible(true);

        // Giả sử frmLogin có phương thức để lấy tên đăng nhập
        String tenDangNhap = frmLogin.getTenDangNhap();

        if (tenDangNhap != null) {
            NguoiDungBusiness bus = new NguoiDungBusiness();
            NguoiDung objUser = bus.layThongTinDangNhap(tenDangNhap);

            if (objUser != null) {
                String quyen = objUser.getQuyen(); // Lấy quyền của người dùng từ cơ sở dữ liệu

                kiemTraQuyenSuDung(quyen, objUser.getTenDangNhap());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Đăng nhập thất bại. Tài khoản không tồn tại.");
            }
        }
    }

    public static void kiemTraQuyenSuDung(String quyen, String userName) {
        boolean isQuyenAdmin = "admin".equals(quyen);
        boolean isQuyenUser = "user".equals(quyen);
        boolean isQuyenStaff = "staff".equals(quyen);

        menuItemDangNhap.setVisible(!isQuyenAdmin && !isQuyenUser && !isQuyenStaff);
//      menuItemDangKy.setVisible(!isQuyenAdmin  &&  !isQuyenUser &&  !isQuyenStaff);

        menuItemDangXuat.setVisible(isQuyenAdmin || isQuyenUser || isQuyenStaff);

        menuNgiepVu.setVisible(isQuyenAdmin || isQuyenUser || isQuyenStaff);
        menuItemTaoHoaDonBanHang.setVisible(isQuyenAdmin || isQuyenStaff);
        menuItemTaoHoaDonMua.setVisible(isQuyenUser || isQuyenAdmin);
//      menuItemNhapHang.setVisible(isQuyenAdmin || isQuyenStaff);

        menuHangHoa.setVisible(isQuyenAdmin || isQuyenUser || isQuyenStaff);
        menuItemHangHoa.setVisible(isQuyenAdmin || isQuyenUser || isQuyenStaff);
        menuItemHoaDonBanHang.setVisible(isQuyenAdmin || isQuyenStaff);
        menuItemHoaDonMua.setVisible(isQuyenAdmin || isQuyenUser );
//        menuItemPhieuNhap.setVisible(isQuyenAdmin || isQuyenStaff || isQuyenStaff);

        menuItemTaiKhoan.setVisible(isQuyenAdmin || isQuyenUser || isQuyenStaff);
        menuItemNguoiDung.setVisible(isQuyenAdmin);
        menuItemKhachHang.setVisible(isQuyenAdmin || isQuyenStaff);

        if (userName != null) {
            lblTrangThai.setText(userName);
            lblDangNhap.setText("Bạn đang đăng nhập với tài khoản: ");
        } else {
            lblTrangThai.setText("Chưa đăng nhập!");
            lblDangNhap.setText("");
        }
    }

    /*private void kiemTraQuyenSuDung(boolean isQuyen) {
        menuItemDangNhap.setVisible(!isQuyen);
        menuItemDangXuat.setVisible(isQuyen);
        menuItemNguoiDung.setVisible(!isQuyen);
        menuNgiepVu.setEnabled(isQuyen);
        menuHangHoa.setEnabled(isQuyen);

        if (isQuyen) {
            lblTrangThai.setText("" + userName);
            lblDangNhap.setText("Bạn đang đăng nhập với tài khoản: " );

        } else {
            lblTrangThai.setText("Chưa đăng nhập!");
            lblDangNhap.setText("" );
        }
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private static javax.swing.JLabel lblDangNhap;
    private static javax.swing.JLabel lblTrangThai;
    private static javax.swing.JMenu menuHangHoa;
    private static javax.swing.JMenu menuHeThong;
    private static javax.swing.JMenuItem menuItemDangNhap;
    private static javax.swing.JMenuItem menuItemDangXuat;
    private static javax.swing.JMenuItem menuItemHangHoa;
    private static javax.swing.JMenuItem menuItemHoaDonBanHang;
    private static javax.swing.JMenuItem menuItemHoaDonMua;
    private static javax.swing.JMenuItem menuItemKhachHang;
    private static javax.swing.JMenuItem menuItemNguoiDung;
    private static javax.swing.JMenuItem menuItemTaiKhoan;
    private static javax.swing.JMenuItem menuItemTaoHoaDonBanHang;
    private static javax.swing.JMenuItem menuItemTaoHoaDonMua;
    private static javax.swing.JMenuItem menuItemThoat;
    private static javax.swing.JMenu menuNgiepVu;
    private static javax.swing.JMenu menuTroGiup;
    // End of variables declaration//GEN-END:variables
}
